//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace feria_virtual_web
{


    public partial class Contact
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new feria_virtual_web.SiteMaster Master
        {
            get
            {
                return ((feria_virtual_web.SiteMaster)(base.Master));
            }
        }
    }
}
